# Generated by Django 5.1 on 2024-08-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
